config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  root 'public#home'

  get 'public/home'

  devise_for :users, path: 'users', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }, skip: [:registrations]

  as :user do
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users' => 'devise/registrations#update', as: 'user_registration'
  end

  resources :accounts, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
    member do
      patch :refresh
    end
    collection do
      patch :refresh_current
    end
  end

  resources :strategies, only: [:index] do
    resources :user_strategies, only: [:new, :edit, :show]
    collection do
      get :favourites
    end
  end

  resources :user_strategies, only: [:create, :update] do
    resources :activities, only: [] do
      collection do
        get    :delete
        delete :destroy
      end
    end
  end

  resources :charts, only: [:index] do
    collection do
      get :config, action: :charts_config, defaults: { format: 'json' }
      get :symbols, defaults: { format: 'json' }
      get :search, defaults: { format: 'json' }
      get :history, defaults: { format: 'json' }
      get :marks, defaults: { format: 'json' }
      get :timescale_marks, defaults: { format: 'json' }
      get :time, defaults: { format: 'json' }
      get :quotes, defaults: { format: 'json' }
    end
  end
end

app/views/shared/_footer.html.haml
%footer.footer.fixed-bottom
  .container-fluid.border-t
    %p.text-center.text-muted.text-truncate
      = "#{t('copyright')} #{Date.today.year} #{t('dreambot')}. #{t('all_rights_reserved')}.".html_safe

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{ class: "alert alert-#{flash_status(name)}" }
      %button.close{ type: 'button', aria: { hidden: 'true' }, data: { dismiss: 'alert' } }
        &times;
      = content_tag :div, msg, id: "flash-#{name}"
- flash.clear

app/views/shared/_modal.html.haml
.modal.fade{ data: { id: 'id' }, tabindex: '-1', role: 'dialog', aria: { labelledby: 'confirm-modal-label', hidden: 'true' } }
  .modal-dialog{ role: 'document' }
    .modal-content
      .modal-header
        %button.close{ type: 'button', data: { aria: { label: "#{t('modal.close')}" }, dismiss: 'modal' } }
          %span{ aria: { hidden: 'true' } }
            &times;
        %h5#confirm-modal-label.modal-title
          = t('modal.confirm')
      .modal-body
        = local_assigns[:body] || t('modal.are_you_sure')
      .modal-footer
        %button.btn.btn-secondary{ type: 'button', data: { dismiss: 'modal' } }
          = t('modal.cancel')
        %button.btn.btn-primary{ type: 'button' }
          = t('modal.ok')

app/views/shared/_navigation.html.haml
- gravatar_url = gravatar_image_url(current_user.email) if current_user
- gravatar_default_url = '1aedb8d9dc4751e229a335e371db8058'
%header.navbar.navbar-full.fixed-top.navbar-expand.navbar-light.bg-white.border-b{ class: live_or_practice, role: 'banner' }
  = link_to brand_icon_path, class: "navbar-brand" do
    .text-lowercase
      .text-primary
        %span.font-db.font-weight-light
          1
  %nav.nav.navbar-nav.ml-auto
    - unless user_signed_in?
      .form-inline
        = link_to t('sign_in'), new_user_session_path, class: 'nav-item nav-link- btn btn-outline-primary'
    - if user_signed_in?
      .form-inline
        .nav-item.dropdown#user-dropdown
          = link_to '#', class: 'nav-link dropdown-toggle pr-0', role: 'button', aria: { haspopup: 'true', expanded: 'false' }, data: { toggle: 'dropdown' } do
            = current_user
            - if gravatar_url.include?(gravatar_default_url)
              .fa.fa-user-circle-o.fa-2x{ class: "text-#{account_practice_or_live_class(current_user.current_account)}" }
            - else
              = gravatar_image_tag(current_user.email, class: "rounded-circle border border-2 border-#{account_practice_or_live_class(current_user.current_account)}")
          .dropdown-menu.dropdown-menu-right.mt-4
            - if current_user.current_account
              .dropdown-item.py-3.px-5
                .lead
                  = current_user.current_account.alias
                  .text-muted#current-balance
                    = "$ #{current_user.current_account.balance}"
                .text-muted#current-balance
                  = "#{current_user.current_account.trade_account_id}"
                .lead
                  = account_practice_or_live_icon(current_user.current_account)
                  = account_max_concurrent_trades_icon(current_user.current_account)
                .mt-2
                  .progress#margin-clouseout-percent
                    = account_margin_clouseout_percent_icon(current_user.current_account)
            = link_to charts_path, class: 'dropdown-item py-3 px-5' do
              .fa.fa-object-group.pr-4
              = t('charts')
            = link_to strategies_path, class: 'dropdown-item py-3 px-5' do
              .fa.fa-area-chart.pr-3
              = t('strategies')
            = link_to accounts_path, class: 'dropdown-item py-3 px-5' do
              .fa.fa-group.pr-3
              = t('accounts')
            = link_to edit_user_registration_path, class: 'dropdown-item py-3 px-5' do
              .fa.fa-user.pr-3
              = t('profile')
            .dropdown-divider
            = link_to destroy_user_session_path, class: 'dropdown-item py-3 px-5', method: :delete do
              .fa.fa-circle-o-notch.pr-1
              = t('sign_out')

app/views/shared/_sounds.html.haml
.d-none
  // https://www.zapsplat.com
  = audio_tag 'bell_small.mp3', class: 'sound-bell'
  = audio_tag 'household_flashlight_button_press.mp3', class: 'sound-button-press'
  = audio_tag 'multimedia_button_click_1.mp3', class: 'sound-button-press-2'
  = audio_tag 'dustyroom_cartoon_bubble_pop.mp3', class: 'sound-bubble'
  = audio_tag 'arcade_game_fruit_machine_jackpot.mp3', class: 'sound-cash-register'
  = audio_tag 'cartoon_punch.mp3', class: 'sound-punch'
  = audio_tag 'car_explosion_debris.mp3', class: 'sound-explosion'
  = audio_tag 'fire-long.mp3', class: 'sound-fire'
  = audio_tag 'scifi_terminal.mp3', class: 'sound-terminal'
  = audio_tag 'multimedia_rollover_1.mp3', class: 'sound-rollover'