config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  root 'public#home'

  get 'public/home'

  devise_for :users, path: 'users', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }, skip: [:registrations]

  as :user do
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users' => 'devise/registrations#update', as: 'user_registration'
  end

  resources :accounts, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
    member do
      patch :refresh
    end
    collection do
      patch :refresh_current
    end
  end

  resources :strategies, only: [:index] do
    resources :user_strategies, only: [:new, :edit, :show]
    collection do
      get :favourites
    end
  end

  resources :user_strategies, only: [:create, :update] do
    resources :activities, only: [] do
      collection do
        get    :delete
        delete :destroy
      end
    end
  end

  resources :charts, only: [:index] do
    collection do
      get :config, action: :charts_config, defaults: { format: 'json' }
      get :symbols, defaults: { format: 'json' }
      get :search, defaults: { format: 'json' }
      get :history, defaults: { format: 'json' }
      get :marks, defaults: { format: 'json' }
      get :timescale_marks, defaults: { format: 'json' }
      get :time, defaults: { format: 'json' }
      get :quotes, defaults: { format: 'json' }
    end
  end
end

app/models/user_strategy.rb
class UserStrategy < ApplicationRecord
  belongs_to :account
  belongs_to :strategy
  has_many :activities, dependent: :destroy

  delegate :name, :worker_name, :instrument, :description, :market_open_at, :market_close_at, :trade_from, :trade_to, 
           :exit_friday_at, :default_config, :trading_hours, :market_hours,
           to: :strategy

  enum state: [:stopped, :started, :paused, :halted, :temporary_halted]

  serialize :config, Hash

  scope :favourite, -> { where(favourite: true) }
  scope :active,    -> { where.not(state: :stopped) }

  def instrument_already_trading?
    account.user_strategies.joins(:strategy).where('strategies.instrument = ?', instrument).started.any?
  end

  def take_profit_at
    self[:take_profit_at] || default_config[:take_profit_at]
  end

  def stop_loss_at
    self[:stop_loss_at] || default_config[:stop_loss_at]
  end

  def margin
    self[:margin] # || default_config[:margin]
  end

  def chart_interval
    self[:chart_interval] || default_config[:chart_interval]
  end

  def units
    self[:units] || default_config[:units]
  end

  def consecutive_losses_allowed
    self[:consecutive_losses_allowed] || default_config[:consecutive_losses_allowed]
  end

  # TODO: When upgrading to Rails 5.1, remove and see if the UTC time from the DB is converted to the timezone.
  def cut_off_time
    self[:cut_off_time].try(:in_time_zone) || market_close_at
  end

  # TODO: When upgrading to Rails 5.1, remove and see if the time is converted from the timezone to UTC before saving to DB.
  def cut_off_time=(value)
    self[:cut_off_time] = Time.new(*value.to_a.sort.collect{ |array| array[1] })
  end
end

app/controllers/user_strategies_controller.rb
class UserStrategiesController < ApplicationController
  before_action :set_user_strategy, only: [:show, :edit, :update, :destroy]
  before_action :set_strategy, only: [:show, :new]
  before_action :set_activities, only: [:show]

  # # GET /user_strategies
  # def index
  #   @user_strategies = UserStrategy.all
  # end

  # GET /strategies/:strategy_id/user_strategies/:id
  def show
  end

  # GET /strategies/:strategy_id/user_strategies/new
  def new
    flash[:warning] = t('messages.set_strategy_config_to_trade_with')
    @user_strategy = UserStrategy.new(strategy: @strategy)
  end

  # GET /strategies/:strategy_id/user_strategies/:id/edit
  def edit
  end

  # POST /user_strategies
  def create
    @user_strategy = current_user.current_account.user_strategies.new(user_strategy_params)
    respond_to do |format|
      if @user_strategy.save
        format.html { redirect_to favourites_strategies_path, notice: t('messages.config_updated') }
      else
        format.html { render :new }
      end
    end
  end

  # NOTE: See link below for $.rails.disableFormElement used in update.js.erb
  # https://github.com/rails/jquery-ujs/blob/master/src/rails.js??
  #
  # PATCH/PUT /user_strategies/:id
  def update
    respond_to do |format|
      format.js   { render 'update', locals: { id: @user_strategy.id, trigger: params[:user_strategy][:trigger] } }
      format.html {
        if @user_strategy.update(user_strategy_params)
          StrategyPublish.publish_to_worker(@user_strategy, @user_strategy.state)
          redirect_to favourites_strategies_path, notice: t('messages.config_updated')
        else
          render :edit
        end
      }
    end
  end

  # # DELETE /user_strategies/:id
  # def destroy
  #   @user_strategy.destroy
  #   respond_to do |format|
  #     format.html { redirect_to user_strategies_url, notice: 'User strategy config was successfully destroyed.' }
  #     format.json { head :no_content }
  #     format.js   { head :ok }
  #   end
  # end

  private

  def user_strategy_params
    params.require(:user_strategy).permit(:user_id, :strategy_id, :trigger, :favourite, :config, :margin, :take_profit_at, :stop_loss_at, :cut_off_time, :chart_interval, :units, :consecutive_losses_allowed)
  end

  def set_user_strategy
    @user_strategy = current_user.current_account.user_strategies.find(params[:id])
  end

  def set_strategy
    @strategy = Strategy.find(params[:strategy_id])
  end

  def set_activities
    @activities = @user_strategy.activities.order(id: :desc).page(params[:page]).per(params[:per_page])
  end
end

app/helpers/user_strategies_helper.rb
module UserStrategiesHelper
end

app/views/user_strategies/_form.html.haml
= form_for @user_strategy, html: { role: 'form' } do |f|
  = f.hidden_field :strategy_id, value: params[:strategy_id]
  .row.form-group
    .col-8.offset-4
      .custom-control.custom-checkbox
        = f.check_box :favourite, class: 'custom-control-input'
        = f.label :favourite, class: 'custom-control-label' do
          %span.custom-control-indicator
          %span.custom-control-description
            = t('favourite')
  .row.form-group
    = label :chart_interval, t('chart_interval'), class: 'col-4 col-form-label'
    .col-8
      .input-group
        = f.select :chart_interval, options_for_select(CANDLESTICK_GRANULARITY_IN_WORDS.map{ |key, value| [value, key] }, @user_strategy.chart_interval), {}, { class: 'form-control' }
  .row.form-group
    = label :margin, t('margin'), class: 'col-4 col-form-label'
    .col-8
      .input-group
        = f.text_field :margin, autofocus: true, type: 'number', min: 0.0001, max: 100, step: 'any', class: 'form-control', aria: { describedby: 'margin-help-block' }
        .input-group-append
          %span.input-group-text
            = '%'
      %small.form-text.text-muted#margin-help-block
        = t('descriptions.margin_help_block')
  .row.form-group
    = label :units, t('units'), class: 'col-4 col-form-label'
    .col-8
      .input-group
        = f.text_field :units, type: 'number', class: 'form-control'
  .row.form-group
    = label :consecutive_losses_allowed, t('consecutive_losses_allowed'), class: 'col-4 col-form-label'
    .col-8
      .input-group
        = f.text_field :consecutive_losses_allowed, type: 'number', min: 1, class: 'form-control'
  / .row.form-group
  /   = label :chart_interval, t('chart_interval'), class: 'col-4 col-form-label'
  /   .col-8
  /     .input-group
  /       = f.text_field :chart_interval, autofocus: true, type: 'number', class: 'form-control', aria: { describedby: 'chart-interval-addon' }
  /       %span#chart-interval-addon.input-group-addon
  /         = t('seconds')
  / .row.form-group.has-success
  /   = label :take_profit_at, t('take_profit_at'), class: 'col-4 col-form-label'
  /   .col-8
  /     .input-group
  /       = f.text_field :take_profit_at, type: 'number', class: 'form-control'
  / .row.form-group.has-danger
  /   = label :stop_loss_at, t('stop_loss_at'), class: 'col-4 col-form-label'
  /   .col-8
  /     .input-group
  /       = f.text_field :stop_loss_at, type: 'number', class: 'form-control'
  / .row.form-group.has-warning
  /   = label :margin, t('margin'), class: 'col-4 col-form-label'
  /   .col-8
  /     .input-group
  /       = f.text_field :margin, autofocus: true, type: 'number', class: 'form-control'
  / .row.form-group
  /   = label :cut_off_time, t('cut_off_time'), class: 'col-4 col-form-label'
  /   .col-8
  /     .input-group
  /       = f.time_select :cut_off_time, {}, { class: 'form-control d-inline-block w-auto float-none', type: 'datetime-local' }
  .form-group
    = f.submit t('update'), class: 'btn btn-outline-primary'

app/views/user_strategies/edit.html.haml
.row
  .col-sm-6.offset-sm-3
    %h2.display-3.mb-3
      = @user_strategy.name
    = render 'form'

app/views/user_strategies/index.html.haml
%h1 Listing user_strategies

%table
  %thead
    %tr
      %th User
      %th Strategy
      %th Config
      %th
      %th
      %th

  %tbody
    - @user_strategies.each do |user_strategy|
      %tr
        %td= user_strategy.user
        %td= user_strategy.strategy
        %td= user_strategy.config
        %td= link_to 'Show', user_strategy
        %td= link_to 'Edit', edit_user_strategy_path(user_strategy)
        %td= link_to 'Destroy', user_strategy, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User strategy config', new_user_strategy_path

app/views/user_strategies/new.html.haml
.row
  .col-sm-6.offset-sm-3
    %h2.display-3.mb-3
      = "#{t('edit')} #{t('config')}"
    = render 'form'

app/views/user_strategies/show.html.haml
- content_for(:title, "#{@user_strategy.strategy.worker_name} #{@user_strategy.strategy.instrument}")
.row
  .col-sm-12
    .pull-right
      - if params[:show_charts] == 'true'
        - if params[:all_charts]
          = link_to strategy_user_strategy_path(@user_strategy.strategy.id, @user_strategy.id, show_charts: true), class: 'btn btn-md btn-primary', title: t('back') do
            .fa.fa-bar-chart
        - else
          = link_to strategy_user_strategy_path(@user_strategy.strategy.id, @user_strategy.id, show_charts: true, all_charts: true), class: 'btn btn-md btn-outline-primary', title: t('all_charts') do
            .fa.fa-bar-chart
      - if params[:show_charts] == 'true'
        = link_to strategy_user_strategy_path(@user_strategy.strategy.id, @user_strategy.id, show_charts: false), class: 'btn btn-md btn-outline-primary', title: t('hide_charts') do
          .fa.fa-eye
      - else
        = link_to strategy_user_strategy_path(@user_strategy.strategy.id, @user_strategy.id, show_charts: true), class: 'btn btn-md btn-primary', title: t('show_charts') do
          .fa.fa-eye-slash
    %h2.display-3.text-truncate
      = @user_strategy.name
    %p.mb-3
      / = render partial: 'strategies/strategy_hours', locals: { strategy: @user_strategy.strategy }
      / %br
      = render partial: 'strategies/strategy_tags', locals: { strategy: @user_strategy.strategy }
- if params[:show_charts] == 'true'
  - if params[:all_charts]
    .row
      .col-sm-12
        - for year in 2010..Time.now.year
          %h2.display-3
            = year
          .mb-4
            = column_chart(column_chart_data(@user_strategy, year), colors: ['#5cb85c', '#d9534f'], stacked: true, legend: false)
        %hr
  .row
    .col-sm-12
      %h2.display-3
        = t('year')
      .mb-4
        = column_chart(column_chart_data(@user_strategy, 'year'), colors: ['#5cb85c', '#d9534f'], stacked: true, legend: false)
      %h2.display-3
        = t('week')
      .mb-4
        = column_chart(column_chart_data(@user_strategy, 'week'), colors: ['#5cb85c', '#d9534f'], stacked: true, legend: false)
%div{ id: "strategy-#{@user_strategy.strategy.id}" }
  .row
    .col-sm-12
      .user-strategy-activities-table
        = render partial: 'activities/table', locals: { card: false, no_header: false }

app/views/user_strategies/update.js.erb
<%- case trigger %>
<%- when 'start', 'resume' %>
  var button = $("#strategy-<%= @user_strategy.strategy.id %>-buttons [data-button=start]");
  App.strategy.start("<%= @user_strategy.id %>");
<%- when 'pause' %>
  var button = $("#strategy-<%= @user_strategy.strategy.id %>-buttons [data-button=pause]");
  App.strategy.pause("<%= @user_strategy.id %>");
<%- when 'stop' %>
  var button = $("#strategy-<%= @user_strategy.strategy.id %>-buttons [data-button=stop]");
  App.strategy.stop("<%= @user_strategy.id %>");
<%- end %>

$(button.closest('form')).on('ajax:complete', function(data, status, xhr) {
  setTimeout(function() {
    $.rails.disableFormElement(button);
  }, 13);
});