config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  root 'public#home'

  get 'public/home'

  devise_for :users, path: 'users', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }, skip: [:registrations]

  as :user do
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users' => 'devise/registrations#update', as: 'user_registration'
  end

  resources :accounts, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
    member do
      patch :refresh
    end
    collection do
      patch :refresh_current
    end
  end

  resources :strategies, only: [:index] do
    resources :user_strategies, only: [:new, :edit, :show]
    collection do
      get :favourites
    end
  end

  resources :user_strategies, only: [:create, :update] do
    resources :activities, only: [] do
      collection do
        get    :delete
        delete :destroy
      end
    end
  end

  resources :charts, only: [:index] do
    collection do
      get :config, action: :charts_config, defaults: { format: 'json' }
      get :symbols, defaults: { format: 'json' }
      get :search, defaults: { format: 'json' }
      get :history, defaults: { format: 'json' }
      get :marks, defaults: { format: 'json' }
      get :timescale_marks, defaults: { format: 'json' }
      get :time, defaults: { format: 'json' }
      get :quotes, defaults: { format: 'json' }
    end
  end
end

app/models/strategy.rb
class Strategy < ApplicationRecord
  has_many :user_strategies, dependent: :destroy

  serialize :default_config, Hash

  def trading_hours
    "#{trade_from.try(:to_s, :time)} - #{trade_to.try(:to_s, :time)}"
  end

  def market_hours
    "#{market_open_at.try(:to_s, :time)} - #{market_close_at.try(:to_s, :time)}"
  end
end

app/controllers/strategies_controller.rb
class StrategiesController < ApplicationController
  before_action :ensure_current_account, only: [:index, :favourites]

  # GET /strategies
  def index
    @strategies = Strategy.all.order(worker_name: :asc)
  end

  # GET /strategies/favourites
  def favourites
    # @strategies = current_user.current_account.user_strategies.favourite
    @strategies = Strategy.joins(:user_strategies).where('user_strategies.account_id = :account_id AND user_strategies.favourite = TRUE', account_id: current_user.current_account.id).order(worker_name: :asc)
  end

  private

  def ensure_current_account
    redirect_to accounts_path, notice: t('messages.set_account_to_trade_with') unless current_user.current_account
  end
end

app/helpers/strategies_helper.rb
module StrategiesHelper
  def strategy_active_class(strategy)
    user_strategy = current_user.current_account.user_strategies.where(strategy: strategy).last
    return 'default' unless user_strategy

    case user_strategy.state
    when 'started'
      'primary'
    when 'paused'
      'warning'
    when 'halted'
      'danger'
    when 'temporary_halted'
      'info'
    when 'stopped'
      'default'
    end
  end

  def strategy_worker_name(strategy)
    content_tag(:span, "#{strategy.worker_name}", class: "badge badge-secondary", title: t('worker_name'), data: { toggle: 'tooltip' })
  end

  def strategy_instrument(strategy)
    content_tag(:span, "#{strategy.instrument}", class: "badge badge-secondary", title: t('instrument'), data: { toggle: 'tooltip' })
  end

  def strategy_chart_interval(strategy)
    content_tag(:span, "#{CANDLESTICK_GRANULARITY[(current_user.current_account.user_strategies.where(strategy: strategy).last.try(:chart_interval) || strategy.default_config[:chart_interval])]}", class: "badge badge-info", title: t('chart_interval'), data: { toggle: 'tooltip' })
  end

  def strategy_units_or_percentage(strategy)
    user_strategy       = current_user.current_account.user_strategies.where(strategy: strategy).last
    units_or_percentage = user_strategy ? user_strategy.margin ? "#{user_strategy.margin}%" : user_strategy.units : strategy.default_config[:margin] ? "#{strategy.default_config[:margin]}%" : strategy.default_config[:units]
    title               = user_strategy ? user_strategy.margin ? t('balance_percentage') : t('units') : strategy.default_config[:margin] ? t('balance_percentage') : t('units')  
    content_tag(:span, units_or_percentage, class: "badge badge-success", title: title, data: { toggle: 'tooltip' })
  end

  def strategy_exit_hours(strategy)
    return nil unless strategy.exit_friday_at
    content_tag(:span, "#{strategy.exit_friday_at.to_s(:time)}", class: "badge badge-warning", title: t('exit_friday_at'), data: { toggle: 'tooltip' })
  end

  def strategy_consecutive_losses_allowed(strategy)
    content_tag(:span, "#{current_user.current_account.user_strategies.where(strategy: strategy).last.try(:consecutive_losses_allowed) || strategy.default_config[:consecutive_losses_allowed]}", class: "badge badge-danger", title: t('consecutive_losses_allowed'), data: { toggle: 'tooltip' })
  end

  def strategy_take_profit_icon(strategy)
    content_tag(:span, "TP #{current_user.current_account.user_strategies.where(strategy: strategy).last.try(:take_profit_at) || strategy.default_config[:take_profit_at]}", class: "badge badge-success", title: t('take_profit'), data: { toggle: 'tooltip' })
  end

  def strategy_stop_loss_icon(strategy)
    content_tag(:span, "SL #{current_user.current_account.user_strategies.where(strategy: strategy).last.try(:stop_loss_at) || strategy.default_config[:stop_loss_at]}", class: "badge badge-danger", title: t('stop_loss'), data: { toggle: 'tooltip' })
  end

  def strategy_margin_icon(strategy)
    content_tag(:span, "M #{current_user.current_account.user_strategies.where(strategy: strategy).last.try(:margin) || strategy.default_config[:margin]}", class: "badge badge-warning", title: t('margin'), data: { toggle: 'tooltip' })
  end

  def strategy_config_path(strategy)
    if config = current_user.current_account.user_strategies.find_by_strategy_id(strategy.id)
      edit_strategy_user_strategy_path(strategy.id, config.id)
    else
      new_strategy_user_strategy_path(strategy.id)
    end
  end
end

app/views/strategies/_buttons_config.html.haml
- unless user_strategy
  .d-inline-block
    = link_to new_strategy_user_strategy_path(strategy), title: t('start'), class: 'btn btn-outline-primary' do
      .fa.fa-play
.d-inline-block.float-right
  - if user_strategy
    .d-inline-block
      = button_to delete_user_strategy_activities_path(user_strategy), method: :get, remote: true, class: 'btn btn-outline-danger', form_class: '', title: t('delete_logs'), data: { disable_with: '<i class="fa fa-hourglass"></i>'.html_safe } do
        .fa.fa-fire
  .d-inline-block
    = link_to strategy_config_path(strategy), class: 'btn btn-outline-secondary', title: t('edit') do
      .fa.fa-wrench

app/views/strategies/_buttons_worker.html.haml
- if user_strategy
  - if user_strategy.started?
    .d-inline-block
      = button_to user_strategy_path(user_strategy), params: { user_strategy: { trigger: :pause } }, method: :patch, remote: true, class: 'btn btn-outline-primary', form_class: '', title: t('pause'), data: { button: 'pause', disable_with: '<i class="fa fa-hourglass"></i>'.html_safe } do
        .fa.fa-pause
    .d-inline-block
      = button_to user_strategy_path(user_strategy), params: { user_strategy: { trigger: :stop } }, method: :patch, remote: true, class: 'btn btn-outline-danger', form_class: '', title: t('stop'), data: { button: 'stop', disable_with: '<i class="fa fa-hourglass"></i>'.html_safe, confirm: t('modal.are_you_sure') } do
        .fa.fa-stop
  - if user_strategy.paused? || user_strategy.halted? || user_strategy.temporary_halted?
    .d-inline-block
      = button_to user_strategy_path(user_strategy), params: { user_strategy: { trigger: :resume } }, method: :patch, remote: true, class: 'btn btn-outline-primary', form_class: '', title: t('start'), data: { button: 'start', disable_with: '<i class="fa fa-hourglass"></i>'.html_safe } do
        .fa.fa-play
    .d-inline-block
      = button_to user_strategy_path(user_strategy), params: { user_strategy: { trigger: :stop } }, method: :patch, remote: true, class: 'btn btn-outline-danger', form_class: '', title: t('stop'), data: { button: 'stop', disable_with: '<i class="fa fa-hourglass"></i>'.html_safe, confirm: t('modal.are_you_sure') } do
        .fa.fa-stop
  - if user_strategy.stopped?
    .d-inline-block
      = button_to user_strategy_path(user_strategy), params: { user_strategy: { trigger: :start } }, method: :patch, remote: true, class: 'btn btn-outline-primary', form_class: '', title: t('start'), data: { button: 'start', disable_with: '<i class="fa fa-hourglass"></i>'.html_safe } do
        .fa.fa-play

app/views/strategies/_card.html.haml
.col-12.col-sm-6.col-lg-4.col-xl-3.px-0.px-sm-3
  .card.mb-3{ id: "strategy-#{strategy.id}", class: "border-#{strategy_active_class(strategy)}" }
    .card-body.pb-0
      %h4.display-4.card-title.text-truncate
        = strategy.name
      %p.card-text
        / = render partial: 'strategy_hours', locals: { strategy: strategy }
        / %br
        = render partial: 'strategy_tags', locals: { strategy: strategy }
      .activities-block.text-truncate{ id: "strategy-#{strategy.id}-activities" }
        = render partial: 'card_activities', locals: { strategy: strategy, user_strategy: user_strategy }
    .card-footer
      %div{ id: "strategy-#{strategy.id}-buttons" }
        %div.d-inline{ id: "strategy-#{strategy.id}-buttons-worker" }
          = render partial: 'buttons_worker', locals: { strategy: strategy, user_strategy: user_strategy }
        %div.d-inline{ id: "strategy-#{strategy.id}-buttons-config" }
          = render partial: 'buttons_config', locals: { strategy: strategy, user_strategy: user_strategy }

app/views/strategies/_card_activities.html.haml
- if user_strategy
  - @activities = user_strategy.activities.order(id: :desc).page(params[:page]).per(6)
  .activities-table.table-sm
    = link_to strategy_user_strategy_path(strategy.id, user_strategy.id), data: { turbolinks: false }, class: 'text-muted' do
      = render partial: 'activities/table', locals: { card: true, no_header: true }

app/views/strategies/_cards.html.haml
.row
  - @strategies.each do |strategy|
    - user_strategy = current_user.current_account.user_strategies.where(strategy: strategy).last
    = render partial: 'card', locals: { strategy: strategy, user_strategy: user_strategy }

app/views/strategies/_strategy_hours.html.haml
%small.d-inline-block.text-muted{ title: t('market_hours'), data: { toggle: 'tooltip', placement: 'top' } }
  = "#{strategy.market_hours}"
%small.d-inline-block.text-muted{ title: t('trading_hours'), data: { toggle: 'tooltip', placement: 'top' } }
  = " (#{strategy.trading_hours})"
- if strategy.exit_friday_at
  %small.d-inline-block.text-muted{ title: t('exit_friday_at'), data: { toggle: 'tooltip', placement: 'top' } }
    = " [#{strategy.exit_friday_at.to_s(:time)}]"

app/views/strategies/_strategy_tags.html.haml
= strategy_worker_name(strategy)
= strategy_instrument(strategy)
= strategy_chart_interval(strategy)
= strategy_units_or_percentage(strategy)
= strategy_exit_hours(strategy)
= strategy_consecutive_losses_allowed(strategy)

app/views/strategies/favourites.html.haml
- content_for(:title, t('favourite_strategies'))
= render partial: 'cards'

app/views/strategies/index.html.haml
- content_for(:title, t('strategies'))
= render partial: 'cards'