config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  root 'public#home'

  get 'public/home'

  devise_for :users, path: 'users', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }, skip: [:registrations]

  as :user do
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users' => 'devise/registrations#update', as: 'user_registration'
  end

  resources :accounts, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
    member do
      patch :refresh
    end
    collection do
      patch :refresh_current
    end
  end

  resources :strategies, only: [:index] do
    resources :user_strategies, only: [:new, :edit, :show]
    collection do
      get :favourites
    end
  end

  resources :user_strategies, only: [:create, :update] do
    resources :activities, only: [] do
      collection do
        get    :delete
        delete :destroy
      end
    end
  end

  resources :charts, only: [:index] do
    collection do
      get :config, action: :charts_config, defaults: { format: 'json' }
      get :symbols, defaults: { format: 'json' }
      get :search, defaults: { format: 'json' }
      get :history, defaults: { format: 'json' }
      get :marks, defaults: { format: 'json' }
      get :timescale_marks, defaults: { format: 'json' }
      get :time, defaults: { format: 'json' }
      get :quotes, defaults: { format: 'json' }
    end
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :user_strategies, dependent: :destroy

  before_create  :update_attributes
  before_update  :update_attributes
  after_update   :update_current
  before_destroy :validate_no_active_strategies, prepend: true
  before_destroy :delete_attributes

  serialize :summary, Hash

  attr_encrypted :access_token, key: Rails.application.secrets.access_token_key

  scope :current, -> { where(current: true) }

  def initialize(options = {})
    super

    if options[:access_token].present?
      practice   = options[:practice].to_i == 1 ? true : false
      client     = Rails.env.backtest? ? OandaApiV20Backtest.new : OandaApiV20.new(access_token: options[:access_token], practice: practice)
      account_id = (options[:trade_account_id] || client.accounts.show['accounts'].first['id']).strip
      account    = client.account(account_id).summary.show

      if account['account']
        self.trade_account_id = account['account']['id']
        self.alias            = account['account']['alias']
        self.balance          = account['account']['balance']
        self.summary          = account['account']
      end
    end
  end

  def oanda_client
    @oanda_client ||= Rails.env.backtest? ? OandaApiV20Backtest.new : OandaApiV20.new(access_token: access_token, practice: practice)
  end

  def refresh_attributes
    account = oanda_client.account(trade_account_id).summary.show

    if account['account']
      self.alias   = account['account']['alias']
      self.balance = account['account']['balance']
      self.summary = account['account']
    end

    save
  end

  def margin_closeout_percent
    (summary['marginCloseoutPercent'].to_f * 100).round(2)
  end

  private

  def update_attributes
    if alias_changed?
      options = { alias: self.alias }
      oanda_client.account(trade_account_id).configuration(options).update
    end

    data = { action: 'update_redis_keys', practice: practice, account: trade_account_id, max_concurrent_trades: max_concurrent_trades }
    data.merge!(access_token: access_token) if access_token_changed? || encrypted_access_token_changed?

    $rabbitmq_exchange.publish(data.to_json, routing_key: 'qw_account_update')
  end

  def delete_attributes
    data = { action: 'delete_redis_keys', practice: practice, account: trade_account_id, access_token: access_token }
    $rabbitmq_exchange.publish(data.to_json, routing_key: 'qw_account_update')
  end

  def update_current
    if current
      accounts = Account.where(user_id: user_id).where.not(id: id)
      accounts.update_all(current: false)
    end
  end

  def validate_no_active_strategies
    if user_strategies.active.any?
      self.errors.add(:base, I18n.t('messages.account_not_deleted_check_strategies'))
      throw(:abort)
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy, :refresh]

  # GET /accounts
  def index
    @accounts = current_user.accounts.order(:id)
  end

  # GET /accounts/:id
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/:id/edit
  def edit
  end

  # POST /accounts
  def create
    @account = current_user.accounts.new(account_params_on_create)
    respond_to do |format|
      if @account.save
        format.html { redirect_to accounts_path, notice: "#{t('messages.account_successfully_created')} #{t('messages.set_account_to_trade_with')}" }
        format.json { render :show, status: :created, location: @account }
      else
        format.html do
          # @account.errors.full_messages.each { |msg| flash[:error] = msg }
          render :new
        end
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/:id
  def update
    respond_to do |format|
      if @account.update(account_params_on_update)
        format.js   { redirect_to accounts_path }
        format.html { redirect_to accounts_path }
        # format.json { render :show, status: :ok, location: @account }
      else
        format.js   { redirect_to accounts_path, alert: t('messages.account_not_updated') }
        format.html { redirect_to accounts_path, alert: t('messages.account_not_updated') }
        # format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/:id
  def destroy
    respond_to do |format|
      if @account.destroy
        format.html { redirect_to accounts_path, notice: t('messages.account_successfully_destroyed') }
      else
        format.html { redirect_to accounts_path, alert: @account.errors.full_messages.join("\n") }
      end
    end
  end

  # PATCH/PUT /accounts/:id/refresh
  def refresh
    respond_to do |format|
      if @account.refresh_attributes
        format.html { redirect_to accounts_path }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { redirect_to accounts_path, alert: t('messages.account_not_updated') }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/refresh_current
  def refresh_current
    respond_to do |format|
      current_user.current_account.refresh_attributes
      format.js
    end
  end

  private

  def account_params_on_create
    params.require(:account).permit(:trade_account_id, :access_token, :practice, :max_concurrent_trades)
  end

  def account_params_on_update
    params[:account].delete(:access_token) if params[:account][:access_token].blank?
    params.require(:account).permit(:access_token, :current, :alias, :max_concurrent_trades)
  end

  def account_params_on_refresh
    params.require(:accounts)
  end

  def set_account
    @account = current_user.accounts.find(params[:id])
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def account_practice_or_live_class(account)
    account ? account.practice? ? 'success' : 'danger' : 'secondary'
  end

  def account_active_class(account)
    account.current? ? 'primary' : 'default'
  end

  def account_practice_or_live_icon(account)
    account.practice? ? content_tag(:span, t('practice_account'), class: "badge badge-success") : content_tag(:span, t('live_account'), class: "badge badge-danger")
  end

  def account_max_concurrent_trades_icon(account)
    account.practice? ? content_tag(:span, account.max_concurrent_trades, class: "badge badge-success", title: t('max_concurrent_trades'), data: { toggle: "tooltip" }) : content_tag(:span, account.max_concurrent_trades, class: "badge badge-danger", title: t('max_concurrent_trades'), data: { toggle: "tooltip" })
  end

  def account_margin_clouseout_percent_icon(account)
    margin_state = 'success'
    margin_state = 'warning' if account.margin_closeout_percent >= 50
    margin_state = 'danger' if account.margin_closeout_percent >= 75
    content_tag(:span, "#{account.margin_closeout_percent}%", class: "progress-bar bg-#{margin_state}", role: "progressbar", title: t('margin_closeout_percent'), style: "width: #{account.margin_closeout_percent}%;", data: { toggle: "tooltip" }, area: { valuenow: account.margin_closeout_percent, valuemin: 0, valuemax: 100 })
  end

  def account_id(account)
    account.trade_account_id.presence || '--'
  end

  def account_alias(account)
    account.alias.presence || t('account')
  end

  def account_balance(account)
    account.balance.present? ? "$ #{account.balance}" : "$ 0"
  end
end

app/views/accounts/_cards.html.haml
.row
  - @accounts.each do |account|
    .col-12.col-lg-6.col-xl-4.px-0.px-sm-3
      .card.mb-3{ class: "border-#{account_active_class(account)}" }
        .card-body
          %h4.display-4.card-title.text-truncate
            = account_alias(account)
          %p.card-text.text-muted.text-truncate
            = account_balance(account)
            %br
            = account_id(account)
            %br
            = account_practice_or_live_icon(account)
            = account_max_concurrent_trades_icon(account)
            %br
          - if account.current
            .btn.btn-primary
              = t('active_account')
          - else
            = button_to account_path(account), remote: true, method: :put, title: t('trade_with_account'), class: 'btn btn-outline-primary d-inline-block', form_class: 'd-inline-block' do
              = hidden_field :account, :current, value: 1
              = t('trade_with_account')
          .d-inline-block.float-right
            .d-inline-block
              = button_to account_path(account), method: :delete, class: 'btn btn-outline-danger', form_class: '', title: t('delete_account'), data: { disable_with: '<i class="fa fa-hourglass"></i>'.html_safe, confirm: t('modal.are_you_sure_delete_account') } do
                .fa.fa-trash
            .d-inline-block
              = link_to edit_account_path(account), class: 'btn btn-outline-secondary', title: t('edit') do
                .fa.fa-wrench
            .d-inline-block
              = link_to refresh_account_path(account), method: :patch, class: 'btn btn-outline-secondary', title: t('refresh') do
                .fa.fa-refresh

app/views/accounts/_cards_new.html.haml
.row
  .col-12.col-lg-6.col-xl-4.px-0.px-sm-3
    .card.mb-3.border-default.text-muted
      .card-body
        %h4.display-4.card-title.text-truncate
          = t('alias')
        %p.card-text
          = "$ #{t('balance')}"
          %br
          = t('account_id')
          %br
          %span.badge.badge-secondary
            = t('practice_account')
          %span.badge.badge-secondary
            = t('live_account')
        = link_to new_account_path, class: 'btn btn-outline-secondary' do
          = t('add_account')

app/views/accounts/_form.html.haml
= form_for @account, html: { role: 'form' } do |f|
  - if @account.new_record?
    .form-group
      = f.text_field :trade_account_id, autofocus: true, class: 'form-control', placeholder: t('account_id'), value: Rails.env.backtest? ? OandaApiV20Backtest::Account::ACCOUNT_ID : nil
    .form-group
      = f.password_field :access_token, class: 'form-control', placeholder: t('access_token')
    .form-group
      .btn-group.btn-group-toggle{ data: { toggle: 'buttons' } }
        = f.label :practice, class: 'btn btn-outline-primary active' do
          = f.radio_button :practice, '1', checked: true
          = t('practice')
        = f.label :practice, class: 'btn btn-outline-primary' do
          = f.radio_button :practice, '0'
          = t('live')
    .form-group
      = f.number_field :max_concurrent_trades, class: 'form-control', placeholder: t('max_concurrent_trades'), min: 1
      %small.form-text.text-muted
        = t('descriptions.max_concurrent_trades')
    .form-group
      = f.submit t('add'), class: 'btn btn-outline-primary'
  - else
    .form-group
      = f.text_field :trade_account_id, disabled: true, class: 'form-control', placeholder: t('account_id')
    .form-group{ title: t('alias') }
      = f.text_field :alias, autofocus: true, class: 'form-control', placeholder: t('alias')
    .form-group
      = f.password_field :access_token, class: 'form-control', placeholder: t('access_token')
      %small.form-text.text-muted
        = t('descriptions.access_token_update')
    .form-group
      = f.number_field :max_concurrent_trades, class: 'form-control', placeholder: t('max_concurrent_trades'), min: 1
      %small.form-text.text-muted
        = t('descriptions.max_concurrent_trades')
    .form-group
      = f.submit t('update'), class: 'btn btn-outline-primary'

app/views/accounts/_table.html.haml
- @accounts.each do |account|
  %tr{ class: "table-#{account_active_class(account)}" }
    %td.hidden-down
      = account.trade_account_id
    %td
      = account.alias
    %td.hidden-sm-down
      = account.balance
    %td
      = account_practice_or_live_icon(account)
    %td
      - unless account.current
        = button_to account_path(account), remote: true, method: :put, title: t('trade_with_account'), class: 'btn btn-sm btn-primary' do
          = hidden_field :account, :current, value: 1
          .fa.fa-play
    %td

app/views/accounts/edit.html.haml
.row
  .col-sm-6.offset-sm-3
    %h2.display-3.mb-3.text-truncate
      = "#{t('edit')} #{t('account')}"
    = render 'form'

app/views/accounts/index.html.haml
- content_for(:title, t('accounts'))
= render partial: 'cards'
= render partial: 'cards_new'

app/views/accounts/new.html.haml
.row
  .col-sm-6.offset-sm-3
    %h2.display-3.mb-3.text-truncate
      = "#{t('new')} #{t('account')}"
    = render 'form'

app/views/accounts/refresh_current.js.erb
$('#current-balance').html("$ <%= current_user.current_account.balance %>");
$('#margin-clouseout-percent').html("<%= escape_javascript(account_margin_clouseout_percent_icon(current_user.current_account)) %>").promise().then(function() {
  $('#margin-clouseout-percent .progress-bar').tooltip();
});

app/views/accounts/show.html.haml
.row
  .col-sm-12
    %h2.display-3.mb-3.text-truncate
      = t('account')
%dl.row
  %dt.col-sm-3.offset-sm-3
    = t('account_id')
  %dd.col-sm-6
    = @account.trade_account_id
  %dt.col-sm-3.offset-sm-3
    = t('alias')
  %dd.col-sm-6
    = @account.alias
  %dt.col-sm-3.offset-sm-3
    = t('current')
  %dd.col-sm-6
    = @account.current
  %dt.col-sm-3.offset-sm-3
    = t('practice')
  %dd.col-sm-6
    = @account.practice